apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: allocation-api
  labels:
    app: allocation-api
spec:
  replicas: 3
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: allocation-api
  template:
    metadata:
      labels:
        app: allocation-api
    spec:
      containers:
        - name: allocation-api
          image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/offender-management/offender-management-allocation-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 60
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: allocation-api-secrets
                  key: secret_key_base
              value: "production"
            - name: RAILS_MAX_THREADS
              valueFrom:
                secretKeyRef:
                  name: allocation-api-secrets
                  key: rails_max_threads
            - name: WEB_CONCURRENCY
              valueFrom:
                secretKeyRef:
                  name: allocation-api-secrets
                  key: rails_web_concurrency
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: rds_instance_endpoint
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: database_password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: database_name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: database_username
