apiVersion: v1
kind: Service
metadata:
  name: allocation-api
  namespace: offender-management-staging
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: allocation-api
