default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Integer(ENV.fetch("RAILS_MAX_THREADS") { 5 }) %>

development:
  <<: *default
  database: offender-management-allocation-api_development

test:
  <<: *default
  database: offender-management-allocation-api_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
