default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Integer(ENV.fetch("RAILS_MAX_THREADS") { 5 }) %>

development:
  <<: *default
  database: offender-management-allocation-api_development

test:
  <<: *default
  database: offender-management-allocation-api_test

production:
  <<: *default
